language: perl
python:
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION bioconductor-dada2 perl-fastx-reader seqfu vsearch fastp clustalo fasttree 
  - conda activate test-environment
  - python setup.py install

script:
  - bash test/all.sh